version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=felix
      - POSTGRES_PASSWORD=admin@1
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
